### ISSUE TITLE
Mark the crate `#[no_std]`

### ISSUE THREAD

**Issue by vrtgs** [jmg049/i24#6]
as it currently stands I don't see why we shouldn't do this

**Comment by jmg049** [comment]
That was always my plan. I looked into it before your pull request and the only thing prevent it was the Error if I recall correctly. Something which was being addressed in rust 1.8.1 

Might not be relevant anymore though. Will investigate.

**Comment by jmg049** [comment]
Yeah I pulled the latest version and moved as much as could to no_std using core instead of std, but error_in_core is still an unstable feature :( At least it is meant to be in the next update for rust

**Comment by vrtgs** [comment]
you can add a std feature 🙃
